name: Pull Request

on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  pull_request:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: lts/*
      working-directory: ./
      run-commit-lint: true
      run-build: true
  check_docs:
    name: Check code docs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Check docs are up to date
        shell: bash
        run: |
          npm ci --ignore-scripts
          npm run generate:code-docs
          # Add untracked files as empty so they come up in diff
          git add -N .
          # Print changed files and error out if there are changes after generating docs
          git diff --exit-code --name-only
