name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release package to NPM
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js latest LTS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          # == Cache frequently built and/or with large dependencies ==
          # == Eviction policy: not accessed in over 7 days
          # == Limit: 10 GB
          # cache: 'npm'
          # == Path to lock file when using mono repos ==
          # cache-dependency-path: subdir/package-lock.json

      - name: Restore packages
        run: npm ci

      - name: Lint commit messages
        run: npx commitlint --from ${{ github.event.before }} --to ${{ github.event.head }} --verbose

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
